export const TOPIC_LIST_SUCCESS = 'TOPIC_LIST_SUCCESS'
export const TOPIC_LIST_FAILURE = 'TOPIC_LIST_FAILURE'

export const TOPIC_ADD_SUCCESS = 'TOPIC_ADD_SUCCESS'
export const TOPIC_ADD_FAILURE = 'TOPIC_ADD_FAILURE'
